name: CI-CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./app
          severity: CRITICAL,HIGH
          exit-code: 0
          ignore-unfixed: true

      - name: Send email on build failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "❌ Build Failed - ${{ github.repository }}"
          to: ${{ secrets.GMAIL_USER }}
          from: ${{ secrets.GMAIL_USER }}
          body: |
            Build job failed in ${{ github.repository }}
            
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
            
            Check details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  docker-scan:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd app
          docker build -t devops-app:${{ github.sha }} .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: devops-app:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 0
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results.sarif

      - name: Send email on docker-scan failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "❌ Docker Scan Failed - ${{ github.repository }}"
          to: ${{ secrets.GMAIL_USER }}
          from: ${{ secrets.GMAIL_USER }}
          body: |
            Docker scan job failed in ${{ github.repository }}
            
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
            
            Check details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: docker-scan

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            rm -rf devops-assignment
            git clone https://github.com/ManojP4848666/devops-assignment.git
            cd devops-assignment/app

            docker build -t devops-app .
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true
            docker run -d -p 80:3000 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            devops-app

      - name: Send email on deploy failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "❌ Deploy Failed - ${{ github.repository }}"
          to: ${{ secrets.GMAIL_USER }}
          from: ${{ secrets.GMAIL_USER }}
          body: |
            Deploy job failed in ${{ github.repository }}
            
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
            
            Check details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send email on deploy success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "✅ Deploy Successful - ${{ github.repository }}"
          to: ${{ secrets.GMAIL_USER }}
          from: ${{ secrets.GMAIL_USER }}
          body: |
            Deploy successful in ${{ github.repository }}
            
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
            
            Live URL: http://${{ secrets.EC2_HOST }}